#r# Register user
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "first_name": "Issam",
  "last_name": "Kharbache",
  "email": "issam@gmail.com",
  "username":"testissam",
  "password": "issamkh7"
}
